"""Title and content for Templates

Revision ID: b7402dba5894
Revises: df6ca669f6d4
Create Date: 2026-06-06 20:54:40.915308

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7402dba5894"
down_revision: str | Sequence[str] | None = "df6ca669f6d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "templates", sa.Column("title", sa.String(length=255), nullable=False)
    )
    op.add_column("templates", sa.Column("content", sa.Text(), nullable=False))
    op.drop_column("templates", "duration")
    op.drop_column("templates", "content_rotation_settings")
    op.drop_column("templates", "settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "templates",
        sa.Column(
            "settings",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "templates",
        sa.Column(
            "content_rotation_settings",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "templates",
        sa.Column(
            "duration", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("templates", "content")
    op.drop_column("templates", "title")
    # ### end Alembic commands ###
