"""аdd_building_id_and_complex_id

Revision ID: df6ca669f6d4
Revises: cb87e85b5801
Create Date: 2026-06-06 19:33:11.222249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6ca669f6d4'
down_revision: Union[str, Sequence[str], None] = 'cb87e85b5801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screens', sa.Column('complex_id', sa.Integer(), nullable=True))
    op.add_column('screens', sa.Column('building_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_screens_building_id'), 'screens', ['building_id'], unique=False)
    op.create_index(op.f('ix_screens_complex_id'), 'screens', ['complex_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screens_complex_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_building_id'), table_name='screens')
    op.drop_column('screens', 'building_id')
    op.drop_column('screens', 'complex_id')
    # ### end Alembic commands ###
